### ISSUE TITLE
Incorrect (too precise!) conversion of charge units from kCal to e-

### ISSUE THREAD

**Issue by lazaroid** [llazzaro/acpype#2]
### Description
Very, very occasionally, a neutral molecule can end up with a slight, i.e. non-zero charge when converted form an Amber .prmtop file to a Gromacs .top file. (I doubt this would affect many people but you never know!)

### Details
I routinely use acpype as a Python script to convert GAFF topologies (generated using antechamber and tleap) in .prmtop format to .top format suitable for use with Gromacs. Very, very occasionally, a neutral molecule can lead to a system with a slight charge: if this is > 0.001 e, then Gromacs complains about it.

I eventually tracked this down to the conversion between the charge units used by Amber (something in terms of kCal) and e, as used by Gromacs...

Digging into the source of tleap, the conversion factor used (ELECTRONTOKCAL in initio.c) is 18.2223; in acpype.py, the value used (qConv) is 18.222281775. This value comes from a combination of various fundamental constants and, usually, the more precision the better, but this difference in precision can occasionally lead to a subtle change in atomic charges.

In most cases, the difference is negligible: in the system where this became an issue, one atom changed by one digit in the 6th decimal place. However, for a condensed phase simulation comprising many hundred of these molecules, the overall charge added up to over 0.001 e and it was flagged by Gromacs.

Modifying acpype.py to set qConv to be (exactly) 18.2223 solved the problem and the individual molecule, and the large, condensed system, had the expected zero charge.

**Comment by alanwilter** [comment]
Please use the official Acpype here https://github.com/alanwilter/acpype and report issues there. Thanks, Alan

**Comment by llazzaro** [comment]
@alanwilter great that you have an official github repo.  I own acpype at pipy, I can transfer you the ownership.
I created this report several years ago and I was not able to find your repo.

**Comment by llazzaro** [comment]
Updated readme and project description to point to official repo. 
I will archive this repo also
