### ISSUE TITLE
unusual element boron

### ISSUE THREAD

**Issue by fill-10** [llazzaro/acpype#3]
* acpype version: 2019
* Python version: 3.6.4
* Operating System: Centos6

### Description

Trying to use mol2 file to generate GMX .itp and .top files for the ionic liquid Tetrafluoroborate. The input bf4.mol2 file was from the antechamber, with the resp charge from gaussian09. The bf4_AC.frcmod file was from parmchk and manually modified since boron is an unusual element.

### What I Did

acpype -i bf4.mol2 -o gmx -b bf4 -c user -d

OR:
acpype -i bf4.mol2 -o gmx -b bf4 -f bf4_AC.frcmod -c user -d

acpype returned the error info:

ACPYPE FAILED: [Errno 2] No such file or directory: 'tmp'
  File "/home/xubo/py-364/lib/python3.6/site-packages/acpype/scripts/acpype.py", line 3547, in main
    is_sorted=options.sorted, chiral=options.chiral)
  File "/home/xubo/py-364/lib/python3.6/site-packages/acpype/scripts/acpype.py", line 3143, in __init__
    self.setResNameCheckCoords()
  File "/home/xubo/py-364/lib/python3.6/site-packages/acpype/scripts/acpype.py", line 673, in setResNameCheckCoords
    tmpFile = open('tmp', 'r')

However, acpype worked well when I used another routine: prmtop and .inpcrd files were firstly generated and then converted to gmx by acpype. It seemed that there was no way to pass the frcmod file into acpype.

My files are attached here

##--- bf4.mol2 ---##
@<TRIPOS>MOLECULE
MOL
    5     4     1     0     0
SMALL
resp

@<TRIPOS>ATOM
      1 B1          -0.0000    -0.0000    -0.0000 B          1 MOL       0.845901
      2 F1           0.3410     0.2930     1.3190 f          1 MOL      -0.461475
      3 F2           0.6120    -1.1920    -0.3840 f          1 MOL      -0.461475
      4 F3          -1.3830    -0.1340    -0.1030 f          1 MOL      -0.461475
      5 F4           0.4300     1.0320    -0.8310 f          1 MOL      -0.461475
@<TRIPOS>BOND
     1    1    2 1
     1    1    3 1
     1    1    4 1
     1    1    5 1
@<TRIPOS>SUBSTRUCTURE
     1 MOL         1 TEMP              0 ****  ****    0 ROOT

##-----------------------------------------------------------##

##--- bf4_AC.frcmod --- ##
Remark line goes here
MASS
B  10.810         0.000               ATTN, no polarizability parameter

BOND
B -f     290.00   1.390       ATTN, need revision

ANGLE
f -B -f     50.000       109.500   ATTN, need revision

DIHE

IMPROPER

NONBON
  B           2.0100    0.0950             ATTN, need revision

##-----------------------------------------------------------##

**Comment by alanwilter** [comment]
Please use the official Acpype here https://github.com/alanwilter/acpype and report issues there. Thanks, Alan

**Comment by llazzaro** [comment]
Closing, this repo will be archived
